[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specify a more compatible Node.js version
[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
